export const _post = [
  // {
  //   postID: 1,
  //   author: {
  //     ava: "./img/petsla.png",
  //     name: "Leo Asher",
  //   },
  //   publishedTime: "21h",
  //   content: {
  //     text: "Click <a href='https://www.facebook.com/petsla.vn'>Tại đây</a> để nhận quà nè <3",
  //     media: "./img/D21.jpg",
  //   },
  //   user: {
  //     ava: "./img/petsla.png",
  //     username: "Leo Asher",
  //   },
  //   isReacted: false,
  //   reactions: {
  //     like: 0,
  //   },
  //   comments: [
  //     {
  //       cmtID: 1,
  //       viewer: {
  //         ava: "./img/petsla.png",
  //         username: "Leo Asher",
  //       },
  //       commentContent: {
  //         text: "ahihi",
  //         media: "",
  //       },
  //       publishedTime: "19m",
  //     },
  //     {
  //       cmtID: 2,
  //       viewer: {
  //         ava: "./img/petsla.png",
  //         username: "Leo Asher",
  //       },
  //       commentContent: {
  //         text: "Click <a href='https://www.facebook.com/petsla.vn'>Tại đây</a> để nhận quà nè <3",
  //         media: "",
  //       },
  //       publishedTime: "19m",
  //     },
  //   ],
  // },
  // {
  //   postID: 2,
  //   author: {
  //     ava: "./img/petsla.png",
  //     name: "Leo Asher",
  //   },
  //   publishedTime: "21h",
  //   content: {
  //     text: "Click <a href='https://www.facebook.com/petsla.vn'>Tại đây</a> để nhận quà nè <3",
  //     media: "",
  //   },
  //   user: {
  //     ava: "./img/petsla.png",
  //     username: "Leo Asher",
  //   },
  //   isReacted: true,
  //   reactions: {
  //     like: 10,
  //   },
  //   comments: [
  //     {
  //       cmtID: 1,
  //       viewer: {
  //         ava: "./img/petsla.png",
  //         username: "Leo Asher",
  //       },
  //       commentContent: {
  //         text: "ahaha",
  //         media: "",
  //       },
  //       publishedTime: "19m",
  //     },
  //   ],
  // },
];

export const _sidebarHotKeyList = [
  {
    id: 1,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/y8/r/S0U5ECzYUSu.png",
    name: "Friends",
    link: "/",
    newNotices: 0,
  },
  {
    id: 2,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/y5/r/duk32h44Y31.png",
    name: "Watch",
    link: "/",
    newNotices: 3,
  },
  {
    id: 3,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/yH/r/kyCAf2jbZvF.png",
    name: "Pages",
    link: "/",
    newNotices: 99,
  },
  {
    id: 4,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/yD/r/lVijPkTeN-r.png",
    name: "Saved",
    link: "/",
    newNotices: 0,
  },
  {
    id: 5,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/y5/r/PrjLkDYpYbH.png",
    name: "Groups",
    link: "/",
    newNotices: 10,
  },
  {
    id: 6,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/yU/r/D2y-jJ2C_hO.png",
    name: "Marketplace",
    link: "/",
    newNotices: 9,
  },
  {
    id: 7,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/y8/r/he-BkogidIc.png",
    name: "Memories",
    link: "/",
    newNotices: 99,
  },
  {
    id: 8,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/yD/r/CwKNCefmHON.png",
    name: "Ad center",
    link: "/",
    newNotices: 3,
  },
  {
    id: 9,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/y9/r/DHBHg9MEeSC.png",
    name: "Ads Manager",
    link: "/",
    newNotices: 3,
  },
  {
    id: 10,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/y8/r/29AMNpNZ4Vm.png",
    name: "Campus",
    link: "/",
    newNotices: 0,
  },
  {
    id: 11,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/y7/r/GzlvHRE-HFS.png",
    name: "Creator Studio",
    link: "/",
    newNotices: 0,
  },
  {
    id: 12,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/yT/r/cT5nPnO8Wsc.png",
    name: "Crisis Response",
    link: "/",
    newNotices: 0,
  },
  {
    id: 13,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/y5/r/vxMUnHhu6Do.png",
    name: "Emotional Health",
    link: "/",
    newNotices: 0,
  },
  {
    id: 14,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/ys/r/8wTx0Eu2vRq.png",
    name: "Events",
    link: "/",
    newNotices: 0,
  },
  {
    id: 15,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/yv/r/GJ4EaivDaSj.png",
    name: "Facebook Pay",
    link: "/",
    newNotices: 0,
  },
  {
    id: 16,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/yK/r/mAnT0r8GSOm.png",
    name: "Favorites",
    link: "/",
    newNotices: 0,
  },
  {
    id: 17,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/yj/r/n2vd2VduYc1.png",
    name: "Fundraisers",
    link: "/",
    newNotices: 0,
  },
  {
    id: 18,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/yy/r/9bekmF_PzNp.png",
    name: "Gaming Video",
    link: "/",
    newNotices: 0,
  },
  {
    id: 19,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/yo/r/DO-SN-shaZL.png",
    name: "Job",
    link: "/",
    newNotices: 0,
  },
  {
    id: 20,
    img: "https://static.xx.fbcdn.net/rsrc.php/v3/yu/r/AisrwUSvQf8.png",
    name: "Live Videos",
    link: "/",
    newNotices: 0,
  },
];

export const _sideBarContactList = [
  {
    id: 1,
    img: "./img/petsla.png",
    name: "PetsLa",
    link: "/",
    newNotices: 0,
  },
  {
    id: 2,
    img: "./img/leoasher.png",
    name: "Leo Asher",
    link: "/",
    newNotices: 0,
  },
  {
    id: 3,
    img: "./img/D21.jpg",
    name: "Ahihi",
    link: "/",
    newNotices: 0,
  },
  {
    id: 4,
    img: "./img/1.jpg",
    name: "Người yêu 1",
    link: "/",
    newNotices: 0,
  },
  {
    id: 5,
    img: "./img/2.jpg",
    name: "Người yêu 2",
    link: "/",
    newNotices: 0,
  },
  {
    id: 6,
    img: "./img/3.jpg",
    name: "Người yêu 3",
    link: "/",
    newNotices: 0,
  },
  {
    id: 7,
    img: "./img/4.jpg",
    name: "Người yêu 4",
    link: "/",
    newNotices: 0,
  },
  {
    id: 8,
    img: "./img/5.jpg",
    name: "Người yêu 5",
    link: "/",
    newNotices: 0,
  },
  {
    id: 9,
    img: "./img/6.jpg",
    name: "Người yêu 6",
    link: "/",
    newNotices: 0,
  },
  {
    id: 10,
    img: "./img/7.jpg",
    name: "Người yêu 7",
    link: "/",
    newNotices: 0,
  },
  {
    id: 11,
    img: "./img/8.jpg",
    name: "Người yêu 8",
    link: "/",
    newNotices: 0,
  },
  {
    id: 12,
    img: "./img/9.jpg",
    name: "Người yêu 9",
    link: "/",
    newNotices: 0,
  },
  {
    id: 13,
    img: "./img/10.jpg",
    name: "Người yêu 10",
    link: "/",
    newNotices: 0,
  },
  {
    id: 14,
    img: "./img/11.jpg",
    name: "Trùm cuối",
    link: "/",
    newNotices: 0,
  },
  {
    id: 15,
    img: "./img/2.jpg",
    name: "Người yêu 2",
    link: "/",
    newNotices: 0,
  },
  {
    id: 16,
    img: "./img/3.jpg",
    name: "Người yêu 3",
    link: "/",
    newNotices: 0,
  },
  {
    id: 17,
    img: "./img/4.jpg",
    name: "Người yêu 4",
    link: "/",
    newNotices: 0,
  },
  {
    id: 18,
    img: "./img/5.jpg",
    name: "Người yêu 5",
    link: "/",
    newNotices: 0,
  },
  {
    id: 19,
    img: "./img/6.jpg",
    name: "Người yêu 6",
    link: "/",
    newNotices: 0,
  },
];
